version: 2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Go static analysis
    - unused        # Check for unused code
    - misspell      # Fix common misspellings
    - gocritic      # Opinionated Go linter
    - revive        # Fast, configurable, extensible, flexible linter
    - gosec         # Security issues
    - errorlint     # Error wrapping best practices
    - bodyclose     # Check HTTP response bodies are closed
    - unconvert     # Remove unnecessary type conversions
    - goconst       # Find repeated strings for constants
    - gocyclo       # Cyclomatic complexity
    - unparam       # Reports unused function parameters

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Platform-specific, not worth the maintenance burden

  gocyclo:
    min-complexity: 15

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - commentedOutCode
      - unnamedResult

  gosec:
    excludes:
      - G401  # MD5 used for hashing (we use it for checksums, not crypto)

  revive:
    confidence: 0.8

  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor
    - test/output

  exclude-rules:
    # Exclude specific linters for test files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - gocritic

    # Allow file operations in CLI tool
    - text: "G304: Potential file inclusion via variable"
      linters:
        - gosec
      path: opts\.go

    # Allow globals during refactoring
    - text: "G101: Potential hardcoded credentials"
      linters:
        - gosec
      path: setup_test\.go
